### ISSUE TITLE
Figure out how to update the docs on readthedocs.io

### ISSUE THREAD

**Issue by RalfJung** [wlanslovenija/tunneldigger#103]
Looks like updating the docs over at https://tunneldigger.readthedocs.io/en/latest/ does not happen automatically. So who can put doc updates there, and how?

Cc @mitar @kostko

**Comment by mitar** [comment]
Make an username there and I can add you as an admin. And then you can check out.

**Comment by RalfJung** [comment]
I created an account, username `RalfJung`.

**Comment by mitar** [comment]
Added.

**Comment by RalfJung** [comment]
Thanks!

There seems to be a way to use webhooks to do the update automatically: https://docs.readthedocs.io/en/stable/webhooks.html

But it seems you used something more manual? Why that?

**Comment by mitar** [comment]
What manual? It should be on GitHub push to master branch. It is not? What other manual process is there?

Maybe there were some issues compiling things. Sometimes dependencies are not available there, like binary ones. But I think one can mock them or something. Anyway, feel free to try. I do not remember how we had it or why we had it like that.

**Comment by RalfJung** [comment]
> It should be on GitHub push to master branch. It is not?

If that was the case then why did I have to do anything? Once I pressed the "build" button there, the docs got updated, but I had to manually do that.

**Comment by mitar** [comment]
I do not know. Sometimes hooks have to be re-created because keys expire and stuff like that.

**Comment by RalfJung** [comment]
I think I've set up a webhook now; we'll see with the next PR if that worked.

**Comment by lynxis** [comment]
hi @RalfJung does it work for you? Can we close the issue?

**Comment by RalfJung** [comment]
Yeah, looks like the change in dab746cd46fdceb070e0739f4e14a1b7b4a98162 was reflected on https://tunneldigger.readthedocs.io/en/latest/server.html. :)
