### ISSUE TITLE
[Docs] max_tunnels

### ISSUE THREAD

**Issue by yanosz** [wlanslovenija/tunneldigger#136]
Heiho,

for configuration, users choose an upper limit for `max_tunnels`
https://github.com/wlanslovenija/tunneldigger/blob/master/broker/l2tp_broker.cfg.example#L9

From a UX perspective, presenting a configuration option requires the user to choose a valid value.
Nevertheless, neither the comment in the sample config nor https://tunneldigger.readthedocs.org/ help to do so

IMHO the docs should explain, in what way platform (CPU cores, memory, etc.) and kernel perameters (i.e. sysctl.conf) influce reasonable configurations.

If 1024 is a sane configuration in almost all situations - I've no experience, here - it will be helpful to document this.

**Comment by RalfJung** [comment]
> IMHO the docs should explain, in what way platform (CPU cores, memory, etc.) and kernel perameters (i.e. sysctl.conf) influce reasonable configurations.

Yeah, that would be great. Unfortunately, I have no idea about this.

Empirically, our VMs struggle really hard with 256 tunnels, so that's the limit we are using. But this depends not just on server details, it also depends on the typical client workload. I doubt there is general advice we can give here, TBH.

**Comment by yanosz** [comment]
Good point - I've two ideas:

* If 256 is good in your situation, it'd cool to document that. (Hardware, network design, etc.)
* I've no idea to what extent the client workload actually influences the system load - but, that doesn't really matter, imho. If you go down the rabbit hole, you probably end-up using OVS instead of a simple linux bridge to implement QoS (htb, fair queues or simple rate limits). That's out of scope - imho. Let's just document configurations, that are known to be working.

**Comment by yanosz** [comment]
sorry, wrong button
