### ISSUE TITLE
No releases since 2017?

### ISSUE THREAD

**Issue by PolynomialDivision** [wlanslovenija/tunneldigger#145]
Why is no release released since 3 years? :)

**Comment by RalfJung** [comment]
I just use the latest git version. Development is slow enough that a release just doesn't feel worth it.

**Comment by mitar** [comment]
He he. But there are some major changes though, like Python 3 support, session ID and stuff.

I think maybe a new version release is in order, it is easier to pack then upstream, because packages generally depend on released versions.

**Comment by RalfJung** [comment]
I want to tweak our rate limiting some more. Once that's in, I'm fine with a release, but I do not think I will have the time to do the work for that.
