### ISSUE TITLE
Review CI Tooling

### ISSUE THREAD

**Issue by kaechele** [wlanslovenija/tunneldigger#158]
In the light of Travis CI restricting use of their free tier (see https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) we may want to think about re-tooling our CI pipeline.

**Comment by RalfJung** [comment]
We are using travis-ci.org though (the OSS version), not travis-ci.com (the commercial version that provides a free tier to OSS sometimes). It is unclear to me what is changing there, since the blog post above emphasized to be about travis-ci.com.

**Comment by kaechele** [comment]
The .org product is being shut down December 31 and users migrated to the .com one: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by RalfJung** [comment]
Ah, fun. You'd think they'd email people actively using travis-ci.org that the service is being discontinued, but it seems they consider that unnecessary...

Time to move to GitHub Actions, it seems.

**Comment by mitar** [comment]
Hm, I think we could also just ask for OSS minutes. They say:

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.

I think it is pretty clear we are an open source project here which does not plan to misuse them.

> Time to move to GitHub Actions, it seems.

From my understanding, I would doubt this it is really possible to replicate our current setup with multiple docker containers trying to test networking between them.

I have had good success with GitLab CI, [which you can also use just as CI for GitHub only](https://about.gitlab.com/solutions/github/). You can run Docker in Docker there and use that to test things we might need here. So I am suggesting that if porting to GitHub Actions fails, maybe GitLab CI is to try.

**Comment by RalfJung** [comment]
> Hm, I think we could also just ask for OSS minutes. They say:

That would also be an option, yeah. And then we wouldn't have to reconfigure everything.^^

Does anyone want to take care of this?

**Comment by mitar** [comment]
OK, I looked into instructions a bit, to send them an e-mail and I realized we have first to do our homework: we should move CI to travis.com, get free plan, and see how long the current minutes last us. Then we should see how much we are using per month, and then we can write to them to ask for that amount to be given us monthly.

Can somebody do this transfer and see how much minutes we need at all?

**Comment by RalfJung** [comment]
To do that it seems an owner of the "wlanslovenija" org needs to approve travis-ci.com's "GitHub App". I just pressed the button to request this approval, so hopefully you can see this somewhere to give Travis access so repos in here can be added.

**Comment by mitar** [comment]
Already granted. :-)

**Comment by RalfJung** [comment]
I still don't seem to be able to set up CI. I went to https://travis-ci.com/organizations/wlanslovenija/repositories, and added specifically the tunneldigger repo, but then after some time it comes back just saying " We couldn’t find any active repositories you have access to".

**Comment by mitar** [comment]
Hm, I got like 3 request now. I approved all of them.

**Comment by mitar** [comment]
Agh. I tried now few times and I figured it out. So I even gave them access to all repositories and this give me a hint. Because tunneldigger was not listed there either. The reason for that is that it is under "migrate" tab. So it is listed there. Can you try from there?

**Comment by RalfJung** [comment]
For this I need to "join the beta", and I think wlanslovenija also needs to? It is listed as "not admin" here.

**Comment by RalfJung** [comment]
I think you'll have to do these steps as I just don't have the required permissions.^^

**Comment by mitar** [comment]
OK. Migrated. Check things out now.

**Comment by RalfJung** [comment]
That seems to have done it. I'll make a PR to see if it does anything.

**Comment by mitar** [comment]
We should probably keep this open and record here amount of minutes we are using and if we need to apply for more? Or should we reopen then?

**Comment by RalfJung** [comment]
I feel we can tackle the problem "not enough minutes¨ when we get there. Do you have any idea how many minutes we have now?

**Comment by mitar** [comment]
Sounds good.

I think around 1000 minutes. See here current amount we used: https://travis-ci.com/github/wlanslovenija?tab=insights

**Comment by kaechele** [comment]
Free minutes for OSS projects seem to have been a dud: https://news.ycombinator.com/item?id=25338983
