### ISSUE TITLE
How does tunneldigger work compared to l2tp?

### ISSUE THREAD

**Issue by CodingSpiderFox** [wlanslovenija/tunneldigger#163]
And how can I be sure it is secure against eavesdropping?

The website https://wlan-si.net/ gives me a TLS 1.0 / 1.1 warning ... that isn't improving my trust in the project ;)

**Comment by CodingSpiderFox** [comment]
OK I thought L2TP would encrypt by default? Why would anyone not want to encrypt tunnels?

**Comment by RalfJung** [comment]
L2TP does not support encryption, you need to either use it over an encrypted link or put an encrypted link into it.

Our usecase for Tunneldigger is the Freifunk community-run open Wifi network. The Wifi network itself is unencrypted, and the network is open so anyone can join and start doing MITM on the user traffic. Thus the additional security obtained by encrypting the l2tp link is tiny -- it does not help against any reasonable attacker model I can imagine. If the attacker is inside your layer 2 network, encrypting the transport does nothing for you -- you as the user need to use encrypted links such as https anyway.

**Comment by RalfJung** [comment]
This is not an actionable issue or something wrong with the software, so I am going to close it.
