### ISSUE TITLE
How to route packets once tunnel is setup

### ISSUE THREAD

**Issue by bennlich** [wlanslovenija/tunneldigger#77]
Hey, there. I'm trying to test tunneldigger by tunneling from one linux box to another (no mesh network involved). The tunnel itself seems to establish properly, but packets aren't routing as I expect them to.

The l2tp0 interface gets created on the client, and a corresponding l2tpxxx-xxx interface gets created on the broker. Once I bring both interfaces up `ip link set <if-name> up`, I can send pings into one interface and see ARPs come out the other:

```
# on the client
ping -I l2tp0 8.8.8.8
```
```
# on the broker
tcpdump -i l2tp101-101
00:36:29.925663 ARP, Request who-has google-public-dns-a.google.com tell <client-ip>, length 28
```
These ARPs don't seem to go anywhere else though. I must be missing some routing config to get these packets out to the internet. I guess I'm wondering, what's the minimum config (presumably in session hooks) I need to be able to test tunneldigger in this way?

I guess this is more of a basic networking question than a tunneldigger question.

**Comment by RalfJung** [comment]
Yes, this is a general networking question, so you're probably better of at stackoverflow or so -- this is not  a network support forum, and there's not so many people reading this. :) Don't forget to include the output of `ip addr` and `ip route show` in your question.

Tunneldigger is not a ready-made VPN solution, it's a low-level part of a bigger networking stack. If you just want to tunnel, I suggest you go look for something like OpenVPN that doesn't require you to assemble all the pieces yourself.

tunneldigger is not OpenVPN. All it does is provide a layer 2 connection -- like plugging a cable between two computers, but neither end has DHCP or anything like that. OpenVPN takes care of IP assignment and routes, including "how do we route everything through the tunnel without trying to put the tunnel through the tunnel". You will have to manually assign IP addresses on both ends, set up routing through the tunnel on the client, and enable forwarding (and probably NAT) on the broker.

 I can't close issues here though, so I'll let someone else do that.

**Comment by mitar** [comment]
Thanks for providing a reply here, @RalfJung. I will be closing this now. Maybe we should have documentation for some common use cases like this though.

**Comment by mitar** [comment]
Or, maybe somebody can create an Ubuntu network manager UI which just does everything for you. :-)
