### ISSUE TITLE
Understanding tunneldigger vs ip l2tp

### ISSUE THREAD

**Issue by bennlich** [wlanslovenija/tunneldigger#82]
I'm playing around with the `ip l2tp` tool, trying to understand how this stuff works. I thought I would do a simple test:
```
sudo ip l2tp add tunnel tunnel_id 3000 peer_tunnel_id 4000 encap udp local 1.2.3.4 remote 5.6.7.8 udp_sport 5000 udp_dport 6000
```
And I see:
```
RTNETLINK answers: Cannot assign requested address
```
What does this RTNETLINK error mean? It seems like it shows up in a lot of cases (I sometimes see it when using tunneldigger too), but I don't have a good understanding of what it really /means/. In this case, I'm thinking my local and remote ips might be unacceptable?

Looking at how tunneldigger creates a tunnel, it passes a socket into [create_tunnel](https://github.com/wlanslovenija/tunneldigger/blob/master/broker/src/tunneldigger_broker/l2tp.py#L103), and does not explicitly pass in any local and remote addresses and ports. I haven't dug in any deeper yet, but my hunch is that this socket already describes the those addresses and ports. Is that right?

If there's a better place to post questions like this, please let me know! Thanks.

**Comment by xbrs1** [comment]
local 1.2.3.4 -> ip addr of the eth 
remote 5.6.7.8 -> ip addr of the eth remote peer

unless your local peer has an eth with ip 1.2.3.4 and remote peer with 5.6.7.8 it won't work.

**Comment by bennlich** [comment]
Thanks @RalfJung and @xbrs1! I have yet to try @xbrs1's suggestion.

Once I get a better understanding of whats going on under the hood of ip l2tp and tunneldigger, I might post here for posterity, but will close for now.
