### ISSUE TITLE
Python2: End of life is coming soon - port tunneldigger-broker to python3

### ISSUE THREAD

**Issue by pmelange** [wlanslovenija/tunneldigger#92]
Python2 will see it's end-of-life coming at the end of the year.  https://pythonclock.org/

Most specifically, OpenWrt has a discussion going on about dropping python2 at https://github.com/openwrt/packages/issues/8520

It would be great if tunneldigger-broker were to be ported/updated to python3.

**Comment by pmelange** [comment]
There is now an issue in OpenWrt to transition all python2 programs to python3 https://github.com/openwrt/packages/issues/8893

**Comment by kaechele** [comment]
Can be closed

**Comment by RalfJung** [comment]
Indeed, fixed by https://github.com/wlanslovenija/tunneldigger/pull/110 :)
