### ISSUE TITLE
Documentation about netfilter

### ISSUE THREAD

**Issue by niccokunzmann** [wlanslovenija/tunneldigger#95]
The [documentation](https://tunneldigger.readthedocs.io/en/latest/server.html) states:

> In addition the kernel must support network address translation via netfilter, otherwise the tunnels will not work as Tunneldigger uses translation to achieve that all tunnels operate over the same external port.

[Here](https://www.netfilter.org/), I read that this is included in Kernel 2.4.x+ to have this if we have iptables installed.

> netfilter.org is home to the software of the packet filtering framework inside the Linux 2.4.x and later kernel series. Software commonly associated with netfilter.org is iptables.

As I am new to the project in such internals, I am a bit unsure: If I have iptables on my computer, will it work? Will it work if I just have a kernel later than 2.4.x?

**Comment by kaechele** [comment]
Can be closed

**Comment by RalfJung** [comment]
Which PR fixed this?

**Comment by kaechele** [comment]
As per your comment here: https://github.com/wlanslovenija/tunneldigger/pull/96#issuecomment-504133692
you stated that this should be addressed in #94. The author of #96 agreed and closed #96. #94 is merged.
Interestingly #96 actually removed any mention of netfilter other than in the package names.

All this leads me to infer this can be closed.

Also, this will be obsoleted (hopefully soon) by #115
